CREATE TABLE tb_vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100),
    model VARCHAR(100),
    manufacture_year INT,
    color VARCHAR(50),
    price DECIMAL(15,2),
    vehicle_status VARCHAR(20)
);
